export const UPDATE_BACKGROUND_COLOR = 'UPDATE_BACKGROUND_COLOR';
export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE';
export const UPDATE_HEADER_BACKGROUND_COLOR = 'UPDATE_HEADER_BACKGROUND_COLOR';
export const UPDATE_INSET = 'UPDATE_INSET';
export const UPDATE_SHOW_SETTINGS = 'UPDATE_SHOW_SETTINGS';
export const RESET = 'RESET';
