export const ADD_TO_SAVED = 'ADD_TO_SAVED';
export const REMOVE_FROM_SAVED = 'REMOVE_FROM_SAVED';
export const UPDATE_ARRIVALS = 'UPDATE_ARRIVALS';
export const UPDATE_NEAREST = 'UPDATE_NEAREST';
export const UPDATE_ROUTES = 'UPDATE_ROUTES';
export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const UPDATE_STOPS = 'UPDATE_STOPS';
