export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const UPDATE_ARRIVALS = 'UPDATE_ARRIVALS';
export const UPDATE_NEAREST = 'UPDATE_NEAREST';
export const UPDATE_ROUTES = 'UPDATE_ROUTES';
export const UPDATE_SERVICES = 'UPDATE_SERVICES';
export const UPDATE_STOPS = 'UPDATE_STOPS';
